-- Server-side rate limiting for public website lead notifications.
CREATE TABLE IF NOT EXISTS website_lead_rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_fingerprint text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_website_lead_rate_limits_recent
  ON website_lead_rate_limits(client_fingerprint, created_at DESC);

ALTER TABLE website_lead_rate_limits ENABLE ROW LEVEL SECURITY;

-- No client policies: only service-role Edge Functions can access this table.
